name: stableAudio-fixed
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # 1. Installare Python e il core di PyTorch/CUDA con Conda
  - python=3.9
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8.0

  # 2. Installare le dipendenze del progetto (da setup.py) con Pip
  - pip:
      - alias-free-torch==0.0.6
      - auraloss==0.4.0
      - descript-audio-codec==1.0.0
      - einops
      - einops-exts
      - ema-pytorch==0.2.3
      - encodec==0.1.1
      - gradio>=3.42.0
      - huggingface_hub
      - importlib-resources==5.12.0
      - k-diffusion==0.1.1
      - laion-clap==1.1.4
      - local-attention==1.8.6
      - pandas==2.0.2
      - prefigure==0.0.9
      - pytorch_lightning==2.1.0
      - PyWavelets==1.4.1
      - safetensors
      - sentencepiece==0.1.99
      - torchmetrics==0.11.4
      - tqdm
      - transformers==4.46.3
      - v-diffusion-pytorch==0.0.2
      - vector-quantize-pytorch==1.14.41
      - wandb==0.15.4
      - webdataset==0.2.100
      - x-transformers<1.27.0